### PR TITLE
Added Dev-Sec.Io 

### PR DESCRIPTION
**Pull request by Acenl12**
[Added Dev-Sec.Io](https://github.com/simeononsecurity/awesome-hardening/commit/7c40b6813b756e4ceba44b81c8a98add4e9b4943)

### CODE REVIEW

**Comment by simeononsecurity** [comment]
I'm not sure if you've seen how other "awesome" repos work. But link the GitHub source code, not your website. Please and thanks! @Acenl12

**Comment by Acenl12** [comment]
Hi, it's not my website, but an independent organisation for hardening on Linux. 
They have things for puppet, ansible and chef, that's why I listed their main website.  If you click here, you can see that: https://dev-sec.io/baselines/ . I can list on their Ansible role for Linux, and users have to click thorugh to find they other roles? @simeononsecurity  Here on their github they have 54 repos: https://github.com/orgs/dev-sec/repositories

**Comment by simeononsecurity** [comment]
> Hi, it's not my website, but an independent organisation for hardening on Linux. 
> They have things for puppet, ansible and chef, that's why I listed their main website.  If you click here, you can see that: https://dev-sec.io/baselines/ . I can list on their Ansible role for Linux, and users have to click thorugh to find they other roles? @simeononsecurity  Here on their github they have 54 repos: https://github.com/orgs/dev-sec/repositories

Yeah it would make more sense to categorize and include their individual GitHub repos.

**Comment by Acenl12** [comment]
Ok then I will close this pull request and create a new one.

**Pull request closed without merging**
